name: ci

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: [ windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21.0.1
        uses: actions/setup-java@v3
        with:
          java-version: 21.0.1
          distribution: 'zulu'
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: PASSPHRASE
      - name: Build with Gradle
        run: ./gradlew.bat build
        env:
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Create Distribution
        run: .\build_app_windows.bat
      - uses: actions/upload-artifact@v3
        with:
          name: JDKMon Windows
          path: |          
            build/installer
            build/libs


  build-mac:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21.0.1
        uses: actions/setup-java@v3
        with:
          java-version: 21.0.1
          distribution: 'zulu'
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: PASSPHRASE
      - name: Build with Gradle
        run: ./gradlew build
        env:
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Grant execute permission for build_app_macos.sh
        run: chmod +x ./build_app_macos.sh
      - name: Create Distribution
        run: ./build_app_macos.sh
      - uses: actions/upload-artifact@v3
        with:
          name: JDKMon Mac
          path: |
            build/installer
            build/libs


  build-linux:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21.0.1
        uses: actions/setup-java@v3
        with:
          java-version: 21.0.1
          distribution: 'zulu'
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: PASSPHRASE
      - name: Build with Gradle
        run: ./gradlew build
        env:
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Grant execute permission for build_app_linux.sh
        run: chmod +x ./build_app_linux.sh
      - name: Create Distribution
        run: ./build_app_linux.sh
      - uses: actions/upload-artifact@v3
        with:
          name: JDKMon Linux
          path: |
            build/installer
            build/libs